config/routes.rb
Rails.application.routes.draw do
  resources :flats
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def edit
    @flat.save
  end

  def update
    @flat.update(flat_params)
    @flat.save
    redirect_to flat_path(@flat)
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<div class="container">
  <div class="form-group">
    <%= simple_form_for @flat do |f| %>
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :description %>
      <%= f.input :price_per_night %>
      <%= f.input :number_of_guests %>
      <%= f.submit "Validate", class: "btn btn-primary" %>
    <% end %>
    <hr>
    <%= link_to "Back to the list", flats_path, class: "btn btn-primary"%>
  </div>
</div>

app/views/flats/edit.html.erb
<div class="container">
  <h2 class="text-center">Add a new flat</h2>
  <%= render 'form'%>

</div>

app/views/flats/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>All our flats</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <p>You searched for . We found 3 flats out of our 3 on our website.</p>
    </div>
  </div>

  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-sm-4">
        <div class="flat-card">
          <div class="flat-card-image" style="background-image: url(https://images.unsplash.com/photo-1494526585095-c41746248156?w=1200);}">
          </div>
          <div class="flat-card-content">
            <h2><%= flat.name %></h2>
            <h3><%= flat.address %></h3>
            <i class="fas fa-user-friends"></i> <%= flat.number_of_guests %>
            <i class="fas fa-euro-sign"></i> <%= flat.price_per_night %>
          </div>
          <div class="flat-card-action">
            <%= link_to "More info", flat_path(flat), id: "more-info" %>
            <%= link_to "Edit",  edit_flat_path(flat), id: "edit" %>
            <%= link_to "Remove", flat_path(flat.id),
      method: :delete,
      data: { confirm: "Are you sure?" }, id: "remove" %>
          </div>
        </div>
      </div>

  <% end %>
</div>

app/views/flats/new.html.erb
<div class="container">
  <h1 class="text-center">New flat</h1>

    <%= render 'form'%>
</div>

app/views/flats/show.html.erb
<div class="map" style="background-image: url('https://images.unsplash.com/photo-1494526585095-c41746248156?w=1200')">
</div>


<div class="container">
  <div class="row">
    <div class="col-xs-10">
      <div class="flat-show-card">
        <h3><%= @flat.name %></h3>
        <h5><%= @flat.address %></h5>
      </div>
      <div class="flat-show-card">
        <h3>A bit more about this flat...</h3>
        <p><%= @flat.description %></p>
      </div>
    </div>
    <div class="col-xs-2">
      <div class="flat-show-card">
        <h5>Book this place !</h5>
        <form action="">
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">From:</span>
            <input type="text" class="form-control" placeholder="12/10/2017" aria-label="Username" aria-describedby="basic-addon1">
          </div>
          <div class="input-group mt-2">
            <span class="input-group-addon" id="basic-addon1">To:</span>
            <input type="text" class="form-control" placeholder="18/10/2017" aria-label="Username" aria-describedby="basic-addon1">
          </div>
          <input type="submit" value="Book" class="btn btn-success mt-2" style="width: 100%">
        </form>
      </div>
      <div class="flat-show-card">
        <h3>Details !</h3>
        <div class="flex">
          <i class="fas fa-user-friends"></i> <%= @flat.number_of_guests %>
          <i class="fas fa-euro-sign"></i> <%= @flat.price_per_night %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-container">
  <div class="flex-item-logo">
    <%= link_to "Simple Airbnb", flats_path %>
  </div>

  <div class="flex-item">
    <form class="form-inline">
      <input type="text" class="form-control" placeholder="Search">
      <%= link_to "Search", new_flat_path, class: "btn btn-default navbar-btn" %>
      <%= link_to "Add flat", new_flat_path, class: "btn btn-default navbar-btn" %>
    </form>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>